library(DESeq2)
library(tidyverse)
library(clusterProfiler)
library(NMF)
library(ggplot2)
library(pheatmap)
library(ashr)
library(DOSE)
library(enrichplot)
library(org.Hs.eg.db)
library(stringr)

# read in data generated by featureCounts
data <- read.table("Lab/Heatmap/A549.txt", header = T)
sampleNames <- c(paste("Cancer", 1:2), paste("Normal", 1:2))
colnames(data) <- c("exonid", "chr", "start", "end", "strand", "length", sampleNames)
inforData <- data[, c(1:4)]
countData <- as.matrix(data[7:10])
rownames(countData) <- data$exonid

# remove genes without any expression in all samples
keep <- rowSums(countData) >= 1
countData <- countData[keep, ]

# build up data for deseq2
configure <- data.frame("condition" = factor(c(rep("LC", 2), rep("WT", 2))), row.names = sampleNames)
ds <- DESeqDataSetFromMatrix(countData, colData = configure, design = ~condition)

# did the normalization without DESeq2
normalized.ds <- estimateSizeFactors(ds)
sizeFactors(normalized.ds)
counts.sf_normalized <- counts(normalized.ds, normalized=TRUE)
log.norm.counts <- log2(counts.sf_normalized + 1)

# DESeq2 found differential genes
dds <- DESeq(ds)
i = resultsNames(dds)[2]
DEG <- lfcShrink(dds, coef=i, type='ashr')
DEG.sorted <- DEG[order(DEG$padj),]
DEG.gene <- row.names(DEG.sorted)

DEG.genes <- subset(DEG.sorted, padj < 0.05)
DEG.gene <- subset(DEG.genes, log2FoldChange > 1 | log2FoldChange < -1)
DEG.gene <- rownames(DEG.gene)

# 1. Heatmap
DEG.normalized <- log.norm.counts[DEG.gene, ]
jpeg('D:/系统默认/桌面/lung_heatmap.jpg', width=900, height=1000, units='px')
aheatmap(DEG.normalized, Rowv=TRUE, Colv=TRUE, distfun="euclidean", hclustfun="average", scale="row")     
dev.off()

# Up and down genes
up <- subset(DEG.genes, log2FoldChange > 1)
up.gene <- str_split(rownames(up),'[.]',simplify=T)[,1]
down <- subset(DEG.genes, log2FoldChange < -1)
down.gene <- str_split(rownames(down),'[.]',simplify=T)[,1]

up <- select(org.Hs.eg.db, keys=up.gene, columns=c("GENENAME","SYMBOL","ENTREZID", "ENSEMBL"), keytype="ENSEMBL")
down <- select(org.Hs.eg.db, keys=down.gene, columns=c("GENENAME","SYMBOL","ENTREZID", "ENSEMBL"), keytype="ENSEMBL")

# 1. KEGG up (emap and cnet)
kEGG_up <- enrichKEGG(gene=up$ENTREZID, organism='hsa', pvalueCutoff=0.01)
k_up <- setReadable(kEGG_up, 'org.Hs.eg.db', 'ENTREZID')
k_up2 <- pairwise_termsim(k_up)
emapplot(k_up2, max.overlaps = 2000)
cnetplot(k_up2)

# print out table
table_up <- as.data.frame(k_up)
write.csv(table_up, file= 'D:/系统默认/桌面/lung_KEGG_up.csv', row.names=T, quote=F)

# Barplot and dotplot
p <- barplot(k_up2, showCategory=20, title="The KEGG enrichment analysis of up-regulated DEGs")
jpeg('D:/系统默认/桌面/lung_KEGG_up.jpg', width=900, height=1000, units='px')
p
dev.off()

p <- dotplot(k_up2, showCategory=20, title="The KEGG enrichment analysis of up-regulated DEGs")
jpeg('D:/系统默认/桌面/lung_KEGG_up.jpg', width=900, height=1000, units='px')
p
dev.off()

# 2. KEGG down
kEGG_down <- enrichKEGG(gene=down$ENTREZID, organism='hsa', pvalueCutoff=0.01)
k_down <- setReadable(kEGG_down, 'org.Hs.eg.db', 'ENTREZID')
k_down2 <- pairwise_termsim(k_down)
emapplot(k_down2, max.overlaps = 2000)
cnetplot(k_down2)

# print out table
table_down <- as.data.frame(k_down)
write.csv(table_down, file= 'D:/系统默认/桌面/lung_KEGG_down.csv', row.names=T, quote=F)

# Barplot and dotplot
p <- barplot(k_down2, showCategory=20, title="The KEGG enrichment analysis of down-regulated DEGs")
jpeg('D:/系统默认/桌面/lung_KEGG_down.jpg', width=900, height=1000, units='px')
p
dev.off()

p <- dotplot(k_down, showCategory=20, title="The KEGG enrichment analysis of down-regulated DEGs")
jpeg('D:/系统默认/桌面/lung_KEGG_down.jpg', width=900, height=1000, units='px')
p
dev.off()



# 3. GO analysis up
GO_up <- enrichGO(gene=up$ENSEMBL, OrgDb=org.Hs.eg.db, keyType='ENSEMBL', ont='ALL', pAdjustMethod='BH',  pvalueCutoff=0.01)
GO_up <- setReadable(GO_up, 'org.Hs.eg.db', 'ENSEMBL')

table_up <- as.data.frame(GO_up)
write.csv(table_up, file='D:/系统默认/桌面/lung_GO_up.csv', row.names=T, quote=F)

barplot(GO_up, showCategory=5, title="The GO enrichment analysis of up-regulated DEGs", font.size=12, split='ONTOLOGY')+facet_grid(ONTOLOGY~.,scale="free")
p = dotplot(GO_up,showCategory=5, title="The GO enrichment analysis of up-regulated DEGs", font.size=12, split='ONTOLOGY')+facet_grid(ONTOLOGY~.,scale="free")
jpeg('D:/系统默认/桌面/lung_GO_up.jpg', width=900, height=1000, units='px')
p
dev.off()

GO_up <- pairwise_termsim(GO_up)
emapplot(GO_up)
cnetplot(GO_up)

# 4. GO analysis down
GO_down <- enrichGO(gene=down$ENSEMBL, OrgDb=org.Hs.eg.db, keyType='ENSEMBL', ont='ALL', pAdjustMethod='BH',  pvalueCutoff=0.01)
GO_down <- setReadable(GO_down, 'org.Hs.eg.db', 'ENSEMBL')

table_down <- as.data.frame(GO_down)
write.csv(table_down, file='D:/系统默认/桌面/lung_GO_down.csv', row.names=T, quote=F)

barplot(GO_down, showCategory=5, title="The GO enrichment analysis of down-regulated DEGs", font.size=12, split='ONTOLOGY')+facet_grid(ONTOLOGY~.,scale="free")
p = dotplot(GO_down, showCategory=5, title="The GO enrichment analysis of down-regulated DEGs", font.size=12, split='ONTOLOGY')+facet_grid(ONTOLOGY~.,scale="free")
jpeg('D:/系统默认/桌面/lung_GO_down.jpg', width=900, height=1000, units='px')
p
dev.off()

GO_down <- pairwise_termsim(GO_down)
emapplot(GO_down)
cnetplot(GO_down)


